import "../styles/globals.css";
import { Inter } from "next/font/google";
import { HangmanContextProvider } from "@/contexts/hangmanState.context";
import { UsedLetterContextProvider } from "@/contexts/usedLetter.context";
import { SecretWordContextProvider } from "@/contexts/secretWord.context";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ahorcado",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UsedLetterContextProvider>
          <SecretWordContextProvider>
            <HangmanContextProvider>{children}</HangmanContextProvider>
          </SecretWordContextProvider>
        </UsedLetterContextProvider>
      </body>
    </html>
  );
}
