import "../styles/globals.css";
import { Inter } from "next/font/google";

import { HangmanContextProvider } from "@/contexts/hangman.context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ahorcado",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HangmanContextProvider>{children}</HangmanContextProvider>
      </body>
    </html>
  );
}
